#general
root:          results/20250917
run_name:      BaTiO3
seed:          123456
dataset_seed:  123456
append:        true

default_dtype: float64
model_dtype:   float32
allow_tf32:    true

# -- network --
model_builders:
 - allegro_pol.model.Allegro
 - PerSpeciesRescale
 - PairPotentialTerm
 - allegro_pol.model.ForceStressPolarizationOutput
 - RescaleEnergyEtc

pair_style:    ZBL
units:         metal

# cutoff
r_max:             6
avg_num_neighbors: auto

# radial basis
AllegroBesselBasis_trainable: true
num_bessels_per_basis:        8
PolynomialCutoff_p:           6

# symmetry
l_max:  3
parity: o3_full

# Allegro layers
num_layers:                            2
num_tensor_features:                   64
tensors_mixing_mode:                   p
two_body_latent_mlp_latent_dimensions: [64, 64, 64]
two_body_latent_mlp_nonlinearity:      silu
two_body_latent_mlp_initialization:    uniform
latent_mlp_latent_dimensions:          [64, 64, 64]
latent_mlp_nonlinearity:               silu
latent_mlp_initialization:             uniform
latent_resnet:                         true
env_embed_mlp_latent_dimensions:       []
env_embed_mlp_nonlinearity:            null
env_embed_mlp_initialization:          uniform
edge_eng_mlp_latent_dimensions:        [128]
edge_eng_mlp_nonlinearity:             null
edge_eng_mlp_initialization:           uniform

# electric field
irreps_elec_field_sh:         1
electric_field_normalization: 1.0 # mean squared electric field magnitude

# -- data --
dataset:            ase
dataset_file_name:  data/BaTiO3_split/train_val_data.xyz
include_keys:
  - total_energy
  - polarization
  - born_charge
  - polarizability
chemical_symbol_to_type:
    Ba: 0
    Ti: 1
    O:  2


# logging
#wandb:          true
#wandb_project:  BaTiO3
#verbose:        info
#log_batch_freq: 10

# training
n_train:         47
n_val:           6
batch_size:      1
max_epochs:      1000000
learning_rate:   0.001
train_val_split: random
shuffle:         true
metrics_key:     validation_loss

# loss function
loss_coeffs:
  total_energy:
    - 1
    - PerAtomMSELoss
  forces:
    - 1
    - MSELoss
  stress:
    - 1
    - MSELoss
  polarization:
    - 1
    - !!python/object:allegro_pol.pol_loss.FoldedPolLoss {}
  born_charge:
    - 1
    - MSELoss
  polarizability:
    - 1000
    - PerAtomMSELoss

# optimizer
optimizer_name: Adam
optimizer_kwargs:
  amsgrad: false
  betas: !!python/tuple
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.

metrics_components:
  - - forces
    - mae
  - - forces
    - rmse
  - - forces
    - mae
    - PerSpecies: True
  - - total_energy
    - mae
  - - total_energy
    - mae
    - PerAtom: True
  - - stress
    - mae
  - - stress
    - rmse
  - - polarization
    - mae
  - - polarization
    - mae
    - PerAtom: True
  - - polarization
    - mean
    - functional: !!python/object:allegro_pol.pol_loss.FoldedPolLoss {}
  - - born_charge
    - mae  
  - - born_charge
    - mae
    - PerSpecies: True
  - - polarizability
    - mae
  - - polarizability
    - rmse

# lr scheduler, drop lr if no improvement for some epochs
lr_scheduler_name:     ReduceLROnPlateau
lr_scheduler_patience: 500
lr_scheduler_factor:   0.5

early_stopping_upper_bounds:
  cumulative_wall: 604800.

early_stopping_lower_bounds:
  LR: 1.0e-5

early_stopping_patiences:
  validation_loss: 100

global_rescale_shift:           null
global_rescale_shift_trainable: false
global_rescale_scale:           dataset_forces_absmax
global_rescale_scale_trainable: false

